# Form implementation generated from reading ui file 'Gui/ControlWindows.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(859, 609)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setStyleSheet("font:87 18pt \"Arial Black\";\n"
"color:rgb(20, 200, 220)")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.btn_toggle_menu = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_toggle_menu.setStyleSheet("QPushButton{\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color: rgb(20, 200, 220);\n"
"border-radius:5px;\n"
"border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"}")
        self.btn_toggle_menu.setObjectName("btn_toggle_menu")
        self.horizontalLayout.addWidget(self.btn_toggle_menu)
        spacerItem = QtWidgets.QSpacerItem(206, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_minimizar = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_minimizar.setStyleSheet("")
        self.btn_minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Gui/../../Imagenes/Minimizar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_minimizar.setIcon(icon)
        self.btn_minimizar.setIconSize(QtCore.QSize(38, 38))
        self.btn_minimizar.setObjectName("btn_minimizar")
        self.horizontalLayout.addWidget(self.btn_minimizar)
        self.btn_maximizar = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_maximizar.setStyleSheet("")
        self.btn_maximizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Gui/../../Imagenes/Maximizar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_maximizar.setIcon(icon1)
        self.btn_maximizar.setIconSize(QtCore.QSize(32, 32))
        self.btn_maximizar.setObjectName("btn_maximizar")
        self.horizontalLayout.addWidget(self.btn_maximizar)
        self.btn_cerrar = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_cerrar.setStyleSheet("")
        self.btn_cerrar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Gui/../../Imagenes/Cerrar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_cerrar.setIcon(icon2)
        self.btn_cerrar.setIconSize(QtCore.QSize(38, 38))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout.addWidget(self.btn_cerrar)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setStyleSheet("background-color:rgb(0, 85, 127)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setStyleSheet("QFrame{\n"
"background-color:rgb(53,53,79);\n"
"}\n"
"QPushButton{\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color: rgb(20, 200, 220);\n"
"border-radius:5px;\n"
"border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: black;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lbl_bienvenida = QtWidgets.QLabel(parent=self.frame_7)
        self.lbl_bienvenida.setStyleSheet("font-size: 12pt;\n"
"    color: white; /* Blanco para mejor contraste */\n"
"    background-color: transparent; /* Sin fondo */\n"
"font-family: \"Tahoma\", sans-serif;")
        self.lbl_bienvenida.setObjectName("lbl_bienvenida")
        self.verticalLayout_9.addWidget(self.lbl_bienvenida)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btn_catalogos = QtWidgets.QPushButton(parent=self.frame_6)
        self.btn_catalogos.setObjectName("btn_catalogos")
        self.verticalLayout_10.addWidget(self.btn_catalogos)
        self.btn_Personas = QtWidgets.QPushButton(parent=self.frame_6)
        self.btn_Personas.setObjectName("btn_Personas")
        self.verticalLayout_10.addWidget(self.btn_Personas)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_10.addWidget(self.pushButton)
        self.btn_pagos = QtWidgets.QPushButton(parent=self.frame_6)
        self.btn_pagos.setObjectName("btn_pagos")
        self.verticalLayout_10.addWidget(self.btn_pagos)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_10.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_10.addWidget(self.pushButton_4)
        self.btn_cerrarsesion = QtWidgets.QPushButton(parent=self.frame_6)
        self.btn_cerrarsesion.setObjectName("btn_cerrarsesion")
        self.verticalLayout_10.addWidget(self.btn_cerrarsesion)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 8)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_5.setStyleSheet("QFrame{\n"
"background-color: rgb(53, 53, 79)\n"
"}\n"
"QLabel{\n"
"font: 87, 12pt \"Arial Black\";\n"
"background-color: #000000ff;\n"
"color: rgb(20, 200, 220);\n"
"border: 0px solid #14C8DC\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_5)
        self.stackedWidget.setStyleSheet("/* --- ESTILO BASE PARA TODAS LAS PÁGINAS --- */\n"
"QStackedWidget > QWidget {\n"
"    background-color: rgb(53, 53, 79); /* Fondo principal (azul oscuro) */\n"
"    font-family: \"Tahoma\", sans-serif; /* Fuente base limpia */\n"
"}\n"
"\n"
"/* --- TÍTULOS (Ej: \"Control de compras\") --- */\n"
"/* Debes asignar esta propiedad en Qt Designer: cssClass = titulo */\n"
"QLabel[cssClass=\"titulo\"] {\n"
"    font-size: 16pt;\n"
"    font-weight: bold;\n"
"    color: rgb(20, 200, 220); /* Color Cián principal */\n"
"    background-color: transparent; /* Sin fondo */\n"
"}\n"
"\n"
"/* --- ETIQUETAS NORMALES (Ej: \"User:\", \"Nombre del proveedor:\") --- */\n"
"QLabel {\n"
"    font-size: 12pt;\n"
"    color: white; /* Blanco para mejor contraste */\n"
"    background-color: transparent; /* Sin fondo */\n"
"}\n"
"\n"
"/* --- CAMPOS DE ENTRADA (Texto, Listas, Fechas) --- */\n"
"QLineEdit, QComboBox, QDateEdit {\n"
"    font-size: 10pt;\n"
"    color: white;\n"
"    background-color: #000000ff; /* Fondo negro */\n"
"    border: 1px solid rgb(20, 200, 220); /* Borde Cián */\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none; /* Quita la flecha fea del combobox */\n"
"}\n"
"\n"
"/* --- TABLA --- */\n"
"QTableWidget {\n"
"    font-size: 10pt;\n"
"    color: white;\n"
"    background-color: #000000ff; /* Fondo negro */\n"
"    gridline-color: rgb(53, 53, 79); /* Líneas de la cuadrícula */\n"
"    border: 1px solid rgb(20, 200, 220); /* Borde Cián */\n"
"}\n"
"\n"
"/* --- ENCABEZADO DE LA TABLA (Cant, Descripción...) --- */\n"
"QHeaderView::section {\n"
"    background-color: rgb(20, 200, 220); /* Fondo Cián */\n"
"    color: black; /* Texto negro para contraste */\n"
"    font-weight: bold;\n"
"    padding: 4px;\n"
"    border: 1px solid rgb(53, 53, 79);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Inicio = QtWidgets.QWidget()
        self.Inicio.setObjectName("Inicio")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Inicio)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_8 = QtWidgets.QFrame(parent=self.Inicio)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_reloj = QtWidgets.QLabel(parent=self.frame_8)
        self.lbl_reloj.setObjectName("lbl_reloj")
        self.verticalLayout_5.addWidget(self.lbl_reloj)
        self.lbl_logo_inicio = QtWidgets.QLabel(parent=self.frame_8)
        self.lbl_logo_inicio.setText("")
        self.lbl_logo_inicio.setPixmap(QtGui.QPixmap("Gui/../../Imagenes/logo.png"))
        self.lbl_logo_inicio.setObjectName("lbl_logo_inicio")
        self.verticalLayout_5.addWidget(self.lbl_logo_inicio)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lbl_bienvenida_inicio = QtWidgets.QLabel(parent=self.frame_8)
        self.lbl_bienvenida_inicio.setObjectName("lbl_bienvenida_inicio")
        self.horizontalLayout_3.addWidget(self.lbl_bienvenida_inicio)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.Inicio)
        self.Cambiarpass = QtWidgets.QWidget()
        self.Cambiarpass.setObjectName("Cambiarpass")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.Cambiarpass)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_14 = QtWidgets.QFrame(parent=self.Cambiarpass)
        self.frame_14.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_7.setStyleSheet("font-size: 16pt;\n"
"    font-weight: bold;\n"
"    color: rgb(20, 200, 220); /* Color Cián principal */\n"
"    background-color: transparent; /* Sin fondo negro */")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        spacerItem3 = QtWidgets.QSpacerItem(301, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_15.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(parent=self.Cambiarpass)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_16 = QtWidgets.QFrame(parent=self.frame_15)
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.txt_pass_anterior = QtWidgets.QLineEdit(parent=self.frame_16)
        self.txt_pass_anterior.setObjectName("txt_pass_anterior")
        self.verticalLayout_17.addWidget(self.txt_pass_anterior)
        self.txt_pass_nuevo = QtWidgets.QLineEdit(parent=self.frame_16)
        self.txt_pass_nuevo.setObjectName("txt_pass_nuevo")
        self.verticalLayout_17.addWidget(self.txt_pass_nuevo)
        self.caracter = QtWidgets.QLabel(parent=self.frame_16)
        self.caracter.setStyleSheet("color: rgb(224, 27, 36);")
        self.caracter.setObjectName("caracter")
        self.verticalLayout_17.addWidget(self.caracter)
        self.mayus = QtWidgets.QLabel(parent=self.frame_16)
        self.mayus.setStyleSheet("color: rgb(224, 27, 36);")
        self.mayus.setObjectName("mayus")
        self.verticalLayout_17.addWidget(self.mayus)
        self.minus = QtWidgets.QLabel(parent=self.frame_16)
        self.minus.setStyleSheet("color:rgb(224, 27, 36)")
        self.minus.setObjectName("minus")
        self.verticalLayout_17.addWidget(self.minus)
        self.numer = QtWidgets.QLabel(parent=self.frame_16)
        self.numer.setStyleSheet("color: rgb(224, 27, 36);")
        self.numer.setObjectName("numer")
        self.verticalLayout_17.addWidget(self.numer)
        self.caracter_especial = QtWidgets.QLabel(parent=self.frame_16)
        self.caracter_especial.setStyleSheet("color: rgb(224, 27, 36);")
        self.caracter_especial.setObjectName("caracter_especial")
        self.verticalLayout_17.addWidget(self.caracter_especial)
        self.txt_pass_repetir = QtWidgets.QLineEdit(parent=self.frame_16)
        self.txt_pass_repetir.setObjectName("txt_pass_repetir")
        self.verticalLayout_17.addWidget(self.txt_pass_repetir)
        self.verticalLayout_16.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(parent=self.frame_15)
        self.frame_17.setStyleSheet("QFrame{\n"
"background-color:rgb(53,53,79);\n"
"}\n"
"QPushButton{\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color: rgb(20, 200, 220);\n"
"border-radius:5px;\n"
"border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: black;\n"
"}\n"
"")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_aceptar_pass = QtWidgets.QPushButton(parent=self.frame_17)
        self.btn_aceptar_pass.setObjectName("btn_aceptar_pass")
        self.horizontalLayout_7.addWidget(self.btn_aceptar_pass)
        self.btn_cancel_pass = QtWidgets.QPushButton(parent=self.frame_17)
        self.btn_cancel_pass.setObjectName("btn_cancel_pass")
        self.horizontalLayout_7.addWidget(self.btn_cancel_pass)
        self.verticalLayout_16.addWidget(self.frame_17)
        self.verticalLayout_16.setStretch(0, 8)
        self.verticalLayout_16.setStretch(1, 4)
        self.verticalLayout_15.addWidget(self.frame_15)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 8)
        self.stackedWidget.addWidget(self.Cambiarpass)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 8)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Menu de opciones</span></p></body></html>"))
        self.btn_toggle_menu.setText(_translate("Dialog", "<"))
        self.lbl_bienvenida.setText(_translate("Dialog", "Bienvenido(a):"))
        self.btn_catalogos.setText(_translate("Dialog", "Catalogos"))
        self.btn_Personas.setText(_translate("Dialog", "Personas"))
        self.pushButton.setText(_translate("Dialog", "Asistencia"))
        self.btn_pagos.setText(_translate("Dialog", "Pagos"))
        self.pushButton_3.setText(_translate("Dialog", "Evaluaciones"))
        self.pushButton_4.setText(_translate("Dialog", "CambiarPass"))
        self.btn_cerrarsesion.setText(_translate("Dialog", "Cerrar sesion"))
        self.lbl_reloj.setText(_translate("Dialog", "00:00:00"))
        self.lbl_bienvenida_inicio.setText(_translate("Dialog", "Bienvenido al Sistema de Gestión de la Escuela de Música"))
        self.label_7.setText(_translate("Dialog", "Cambiar contraseña"))
        self.txt_pass_anterior.setPlaceholderText(_translate("Dialog", "Password Anteror"))
        self.txt_pass_nuevo.setPlaceholderText(_translate("Dialog", "Password nuevo"))
        self.caracter.setText(_translate("Dialog", "4-10 caracteres"))
        self.mayus.setText(_translate("Dialog", "Al menos una mayuscula"))
        self.minus.setText(_translate("Dialog", "Al menos una minuscula"))
        self.numer.setText(_translate("Dialog", "Al menos un numero"))
        self.caracter_especial.setText(_translate("Dialog", "Al menos un caracter especial(+,*,#,%)"))
        self.txt_pass_repetir.setPlaceholderText(_translate("Dialog", "Repita el password nuevo"))
        self.btn_aceptar_pass.setText(_translate("Dialog", "Aceptar"))
        self.btn_cancel_pass.setText(_translate("Dialog", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
